title: Ryohei Kametaka's Resume
profile_img: /assets/img/profile.jpg
icon_img: /assets/img/favicon.ico

name: "Ryohei Kametaka"
job: "Full-Stack Geospatial Developer"

#phone_number: xxx-xxx-xxxx
#address: Tokyo, Japan
#email: email@example.com
#linkedin_username: linkedin
github_username: ryoheikametaka
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
blog_url: https://ryoheikametaka.com/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag